//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.16 at 11:09:49 AM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://lizo.com.br/countriesServiceV1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package br.com.lizo.countriesservicev1;
